version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - ./data:/data
      - /app/node_modules
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=development
      - HOST=0.0.0.0
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
      - HOST=0.0.0.0
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=3000
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge